server: 
  port: 9094
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/order_details
    username: root
  jpa: 
    generate-ddl: true
    hibernate.ddl-auto: none
    show-sql: true
  profiles: prod
