server: 
  port: 9094
spring: 
  datasource:
    generate-unique-name: false 
    url: jdbc:h2:mem:testdb
  h2: 
    console: 
      enabled: true
  jpa:
    hibernate.ddl-auto: create-drop
    properties: 
      hibernate: 
        format_sql: true
        show_sql: true
        type: trace
        use_sql_comments: true
  profiles: dev
