INSERT INTO CUSTOMER_PAYMENT_DETAILS (ORDERID,AMOUNT) VALUES (1,100EUR);
INSERT INTO CUSTOMER_PAYMENT_DETAILS (ORDERID,AMOUNT) VALUES (2,100EUR);


INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (1, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (2, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (3, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (4, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (5, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (6, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (7, 1,100EUR);
INSERT INTO ORDER_CUSTOMER_DETAILS (ORDERID,CUSTOMERID,AMOUNT) VALUES (8, 1,100EUR);

--Inseting for 2 customer
